language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
cache: pip
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
- pyyaml=pyyaml
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]]; then pyyaml='pyyaml<3.13'; fi
install:
- python3 -m pip install $pyyaml
- python3 -m pip install pydiatra $pyflakes
script:
- python3 -m pydiatra .
- python3 -m pyflakes .
- ./yaml-pyprint .travis.yml

# vim:ts=2 sts=2 sw=2 et
